#!/usr/bin/env bash
# this script  display information about subdomains and domains

domain_info() {
local domain"$1"
local subdomain="$2"

if [ $# -eq 1 ]; then
subdomains=("www" "lb-01" "web-01" "web-02")
else
subdomain("$subdomian")

fi
}
for subdomain in "${subdomains[@]}"; do
    record_type=$(dig +short -t ANY "$subdomain.$domain" | awk 'NR==1 {print $4}')
    destination=$(dig +short "$subdomain.$domain" | awk 'NR==1')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
done

