#!/usr/bin/env bash
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
sed -i '/listen 80 dafault_server/a  rewrite ^/redirect_me http://https://www.youtube.com/ permanent;
'/etc/nginx/sites-available/default
service nginx start
