#!/usr/bin/env bash
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
rewrite ^/redirect_me http://https://www.youtube.com/ permanent;
service nginx start
