#!/usr/bin/env bash
# this script return an HTTP 404 error code
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="server_name _;\n
sudo sed -i 's/server_name_;'"$string_for_replacement"'/' /etc/nginx/sites-enabled/default
sudo service nginx restart
