#!/usr/bin/env bash
# This script add custom Nginx response header
sudo sed -i "/server_name _/ a  add_header  X-Served-By $HOSTNAME;"  /etc/nginx/sites_enabled/default
# this restart
sudo service nginx restart
