#!/usr/bin/env bash
# This script loops from 1 - 20 then 
# displays 4 then bad luck from China for the 4th loop iteration
# displays 9 then bad luck from Japan good luck for the 9th loop iteration
# displays 17 then bad luck from Italy for the 17 loop iteration
n=1
k=20

while [ $n -le $k ]; do
case $n in
4)
echo -e "$n\nbad luck from China"
;;
9)
echo -e "$n\nbad luck from Japan"
;;
17)
echo -e "$n\nbad luck from Italy"
;;
*)
echo "$n"
esac
n=$((n + 1))
done
