#!/usr/bin/env bash
#This script  displays the time for 12 hours and 59 minutes

n=0
k=1
echo "Hour: 0"
while [ $n -le 12 ]; do
    while [ $k -le 59 ]; do
        echo "$k"
        k=$((k + 1))
    done
    n=$((n + 1))
    echo "Hours: 1"
    k=1
done | head -n 70
