#!/usr/bin/env bash
#This script  displays the time for 12 hours and 59 minutes

n=0
while [ $n -le 12 ]; do
	echo "Hour: $n"
	k=1
    while [ $k -le 59 ]; do
         echo "Hour: $k"
        k=$((k + 1))
    done
    n=$((n + 1))
done
