#!/usr/bin/env bash
#This script gives you information about the school file

if [ -e "$school" ]; then
echo "school file exists"
	if [ -s "$school" ]; then
	echo "school file is empty"
	else
	echo "school file is not empty"
	fi
	if [ -f "$school" ]; then
	echo "school is a regular file"
	else
	echo "school is not a regular file"
	fi
echo "school file is not empty"
fi
