#!/usr/bin/env bash
# this script accepts one argument 
# uses whoami command under the user passed as an argument

# thischeck if one argument is provided
if [ $# -eq 1 ]; then
	username="$1"
# this command print  the username using whoami 
sudo -u "$username" whoami
else
	echo "$1"
fi
