#!/usr/bin/env bash
# Configure ssh client so that you can connect to a server without typing a password.
Host

Host 18.204.7.243
     User ubuntu
     IdentityFile ~/.ssh/id_rsa
     PasswordAuthentication  no
