#!/usr/bin/env bash
# Configure ssh client so that you can connect to a server without typing a password.
Host

Host 35.175.132.73
     User ubuntu
     IdentityFile ~/.ssh/school
     PasswordAuthentication  no
